### ISSUE TITLE
If target repo is relative then script tries to use a relative path to the script not the current directory

### ISSUE THREAD

**Issue by DALDEI** [vangorra/git_split#11]
This looks intentional but I cant fathom why
I have git_split.sh in $HOME/bin
repos in /myrepos

cd /myrepos
git init target
git_split  <source-repo>  <branch> relative/path/in/source  target

Errors because it cant find  $HOME/bin/target

/home/dlee/bin/git_split.sh: line 28: cd: /home/dlee/bin/target: No such file or directory

**Comment by vangorra** [comment]
This should be resolved with the latest code. Run a git pull and let me know the results.

**Comment by DALDEI** [comment]
In the mean time I forked this project and made some changes which you may or may not want.
https://github.com/DALDEI/git_split

In addition to the relative directory, I added code that preserves tags and branch commits.
The tags seem to be  working fine, branch merge commits are transferred but branch names are not.
-David
