### ISSUE TITLE
The target directory is not found

### ISSUE THREAD

**Issue by godrose** [vangorra/git_split#7]
Output:
$ ./git_split.sh https://github.com/LogoFX/LogoFX.git master LogoFX.Client.Bootstrapping.Platform logofx-client-bootstrapping
Cloning into '/tmp/git_split.3a5XRZ/repo_base'...
remote: Counting objects: 5819, done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 5819 (delta 52), reused 0 (delta 0), pack-reused 5726
Receiving objects: 100% (5819/5819), 1.42 MiB | 280.00 KiB/s, done.
Resolving deltas: 100% (4552/4552), done.
Checking connectivity... done.
Checking out files: 100% (638/638), done.
/tmp/git_split.3a5XRZ/repo_base/LogoFX.Client.Bootstrapping.Platform doesn't exist or is not a directory.

Steps to reproduce: 
1) Clone LogoFX from https://github.com/LogoFX/LogoFX.git
2) Drop the script at the root level
3) Execute the script with the parameters above.

**Comment by vangorra** [comment]
Latest codebase fixes this issue.

Thanks for reporting!
